NAME = SedIsForLosers
CC = c++
CFLAGS = -W -Wextra -Werror -std=c++98
OBJ_DIR = ./objs

SRCS = main.cpp
OBJS = $(SRCS:%.cpp=$(OBJ_DIR)/%.o)
DEPS = $(OBJS:.o=.d)

vpath %.cpp 

: $(NAME)

$(OBJ_DIR)/%.o: %.cpp
	mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

clean:
	$(RM) -rf $(OBJ_DIR)

fclean: clean
	$(RM) $(NAME)

re: fclean 

-include $(DEPS)

.PHONY:  clean fclean re
